#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InterphoneSAM.Resource", IsApplication=true)]

namespace InterphoneSAM
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Refractored.Xam.TTS.Resource.String.ApplicationName = global::InterphoneSAM.Resource.String.ApplicationName;
			global::Refractored.Xam.TTS.Resource.String.Hello = global::InterphoneSAM.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int MalVt = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int PasHcp = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int SrdMt = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int buttonHangUp = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int buttonPickUp = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int hangUp = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout1 = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int progressBar1 = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int sendTextButton = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int speakButton = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int textToReceive = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int textToSend = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CommunicationBlindNormal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CommunicationDeafMute = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu_Activity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Wait_Activity = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int ring_0 = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
